apiVersion: v1
kind: Service
metadata:
  labels:
    backend.service: backend
  name: backend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    backend.service: backend